export const pricingPlans = [
  {
    name: "Express",
    description:
      "Perfect for startups and solo entrepreneurs looking to launch quickly",
    price: 800,
    features: [
      "1-2 Pages (4-5 sections)",
      "Custom Layout & Design",
      "1 Premium Stock Photo",
      "Mobile Responsive Design",
      "SEO friendly",
      "Social Media Integration",
      "Domain Registration Support",
      "Cross Browser Compatibility",
      "1 Design Revision",
      "Custom quote for support and maintenance",
      "Dedicated Project Manager",
    ],
    additionalServices: [
      "Payment Gateway Integration (additional $300)",
      "CRM Integration (additional $300)",
      "Chat Bot Integration (Custom Quote)",
      "Multi-language Implementation (Custom Quote)",
      "SSL Certificate (Secured HTTPS)",
    ],
  },
  {
    name: "Standard",
    description:
      "Designed for small to mid-sized businesses ready to grow their digital presence",
    price: 1200,
    features: [
      "2-4 Pages (6-9 sections)",
      "Custom Layout & Design",
      "2 Premium Stock Photo",
      "Mobile Responsive Design",
      "SEO friendly",
      "Social Media Integration",
      "Domain Registration Support",
      "Cross Browser Compatibility",
      "2 Design Revision",
      "2 months free support and maintenance",
      "Dedicated Project Manager",
    ],
    additionalServices: [
      "Payment Gateway Integration (additional $300)",
      "CRM Integration (additional $300)",
      "Chat Bot Integration (Custom Quote)",
      "Multi-language Implementation (Custom Quote)",
      "SSL Certificate (Secured HTTPS)",
    ],
  },
  {
    name: "Advanced",
    description:
      "A powerful, scalable solution for established businesses and enterprises",
    price: 1500,
    features: [
      "Upto 8 Pages (upto 14 sections)",
      "$250 per additional page",
      "Custom Layout & Design",
      "3-4 Premium Stock Photo",
      "Mobile Responsive Design",
      "SEO friendly",
      "Social Media Integration",
      "Domain Registration Support",
      "Cross Browser Compatibility",
      "4 Design Revision",
      "3 months free support and maintenance",
      "Dedicated Project Manager",
    ],
    additionalServices: [
      "Payment Gateway Integration (additional $300)",
      "CRM Integration (additional $300)",
      "Chat Bot Integration (Custom Quote)",
      "Multi-language Implementation (Custom Quote)",
      "SSL Certificate (Secured HTTPS)",
    ],
  },
]
